{{- if ((.Values.server.configMaps).create) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-service.fullname" . }}
  {{- with .Values.server.configMaps.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

data:
{{- range .Values.server.configMaps.data }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
{{- end }}
