base-service:
  nameOverride: ping-demo
  fullnameOverride: ping-demo

  server:
    revisionHistoryLimit: 1

    image:
      repository: asia.gcr.io/krystal-operation/krystal/ping-demo
      tag: master-000000000

    serviceAccount:
      create: true

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: test.krystal-holdings.com
          paths:
            - path: /
              pathType: Prefix

    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi

    autoscaling:
      enabled: false

    service:
      port: 8080

  redis:
    enabled: false
