{{- if ((.Values.server.secrets).create) }}
{{- $key := .Values.server.secrets.path | replace "/" "_" -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "base-service.fullname" . }}
spec:
  backendType: gcpSecretsManager
  dataFrom:
  - {{ $key }}
{{- end }}
