{{- if and .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "base-service.redis.fullname" . }}
  labels:
    {{- include "base-service.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 4 }}
    app.kubernetes.io/version: {{ .Values.redis.image.tag | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base-service.name" . }}-{{ .Values.redis.name }}
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base-service.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 8 }}
        app.kubernetes.io/version: {{ .Values.redis.image.tag | quote }}
        {{- with .Values.redis.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.redis.securityContext }}
      securityContext: {{- toYaml .Values.redis.securityContext | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.redis.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ template "base-service.redisServiceAccountName" . }}
      containers:
      - name: {{ template "base-service.redis.fullname" . }}
        args:
        - --save
        - ""
        - --appendonly
        - "no"
        {{- with .Values.redis.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: {{ .Values.redis.image.pullPolicy}}
        {{- if .Values.redis.containerSecurityContext }}
        securityContext: {{- toYaml .Values.redis.containerSecurityContext | nindent 10 }}
        {{- end }}

        {{- if .Values.redis.env }}
        env:
          {{- toYaml .Values.redis.env | nindent 12 }}
        {{- end }}
        {{- if .Values.redis.envFrom }}
        envFrom:
          {{- toYaml .Values.redis.envFrom }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.redis.containerPort }}
          name: redis
        {{- if .Values.redis.volumeMounts }}
        volumeMounts:
{{- toYaml .Values.redis.volumeMounts | nindent 10 }}
{{- end }}
        resources:
{{- toYaml .Values.redis.resources | nindent 10 }}
{{- if .Values.redis.volumes }}
      volumes:
{{- toYaml .Values.redis.volumes | nindent 8}}
{{- end }}
{{- end }}
